#Baaba Nhyira Baidoo
#Time taken: I took 3 hours 40 minutes
#AI used: ChatGPT
#AI prompt: "Create an ASCII with: [Description of what I asked]"
#AI art quality: The quality was good, but I got confused whether it actually looked like the material I wrote.
print("How to make a sandwich instructions:")
print("Wash your hands with soap and clean running water then wipe your hands with a clean hand cloth.")
print("Go to the fridge and take out your bread and ingredients like vegetables (lettuce, onion, carrot,and cabbage), and peanut butter.")
print("Get a clean tray and paper towel on it, then put the paper towel on the clean tray.")
print("When you are done with step 3, wash your vegetables (lettuce, onion, carrot, and cabbage) with clean running water.")
print("When you are done with step 4, put the clean vegetables (lettuce, onion, carrot, and cabbage) on the paper towel that is on the clean tray.")
print("Clean your hand with a clean cloth, then take a clean chopping board and knife. Also get a clean dinner plate.")
print("Put your bread on the chopping board and use the knife to slice the bread into two horizontally but not all the way to the end where the bread should appear like an open book.")
print("After put your sliced bread on the clean dinner plate you took from step 5.")
print("Then take a small bread knife so you can scoop a little peanut butter and spread it on both sides of the bread.")
print("Now, take your clean vegetables (lettuce, onion, carrot,and cabbage) that you placed on the paper towel on the clean tray, and use the knife you used to slice your bread to now chop the vegetables into two and put the other half back into the fridge.")
print("Then use the other half still on the chopping board to slice it with the knife to medium size portion.")
print("After slicing your vegetables, spread them on the sliced bread that is placed on the clean dinner plate.")
print("Then close your bread and now you have a sandwich.")

print("ASCII")
print("Create a ASCII with this: Get a clean tray and paper towel on it then put the paper towel on the clean tray.")
print("|-----------------------------|")
print("|         clean tray          |")
print("|                             |")
print("|  |----------------------|   |")
print("|  |       Paper          |   |")
print("|  |       Towel          |   |")
print("|  |                      |   |")
print("|  |----------------------|   |")
print("|-----------------------------|")

print("Create a ASCII with this: Clean your hand with a clean cloth, then take a clean chopping board and knife. Also get a clean dinner plate.")
print("Chopping Board")
print("|------------------|")
print("|  Chopping Board  |")
print("|                  |")
print("|------------------|")

print("Knife")
print("||")
print("||")
print("||====>")

print("Clean Dinner plate")
print("-----------------")
print("//             //")
print("|    Dinner     |")
print("//   Plate     //")
print("-----------------")

print("Create a ASCII with this:Then take a small bread knife so you can scoop a little peanut butter and spread it on both sides of the bread.")
print("Small Bread Knife")
print("--------------")
print("|            |")
print("--------------")
print("            //")
print("          //  ")
print("        ___   ")
print("     //       ")
print("____      ")

print("Peanut butter")
print("|-----------|")
print("| ^^^^^^^^^ |")
print("| ^^^^^^^^^ |")
print("|-----------|")

print("Bread Both sides")
print("|---------|")
print("| ^^^^^^^ |")
print("|  Bread  |")
print("|---------|")

print("|---------|")
print("| ^^^^^^^ |")
print("|  Bread  |")
print("|---------|")

print("Create a ASCII with this: After slicing your vegetables, spread them on the sliced bread that is placed on the clean dinner plate.")
print("Sliced vegetables")
print(" 0   o   o   o   o")
print("||  ||  ||  ||  ||")
print("oo  oo  oo  oo  oo")

print("Bread with veggies")
print("|----------------------|")
print("|     o   o   o   o     |")
print("|    ||  ||  ||  ||     |")
print("|      Bread            |")
print("|-----------------------|")

print("Dinner plate")
print("-------------------------")
print("//                     //")
print("| |-------------------| |")
print("| |       Veggie      | |")
print("| |       Bread       | |")
print("| |-------------------| |")
print("//                     //")
print("-------------------------")